name: Set up project
description: Sets up Bun and installs dependencies

inputs:
  dev:
    description: Whether to install dev dependencies
    required: false
    default: "true"


runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        key: bun-global-cache-${{ hashFiles('bun.lock') }}-${{ inputs.dev == 'true' && 'dev' || 'prod' }}
        restore-keys: |
          bun-global-cache-${{ hashFiles('bun.lock') }}-
        path: ~/.bun/install/cache

    - name: Install dependencies
      run: bun install --frozen-lockfile ${{ inputs.dev != 'true' && '--production' || '' }}
      shell: sh
